---
language: python
sudo: true
python:
  - "2.7"
install:
  - pip install ansible
before_script:
  - ansible --version
  - sh ./test/before_script.sh
script:
  - [ -f ./test/1/cleanup.sh ] && ./test/1/cleanup.sh
  - ansible-playbook --syntax-check ./test/1/site.yml -i ./test/hosts -t case-1
  - ansible-playbook ./test/1/site.yml -i ./test/hosts -t case-1
  - [ -f ./test/1/test.sh ] && ./test/1/test.sh
