---
# tasks file for roles/systemd/service
- name: Ensure systemd dirs exists
  file: state=directory path="{{ item }}" recurse=yes
  with_items:
    - "{{ systemd_service_default_dir }}"
    - "{{ systemd_service_systemd_dir }}"

- name: Create env files for services
  template: 
    src: "default.j2"
    dest: "{{ systemd_service_default_dir }}/{{ item.key }}.env"
  with_dict: "{{ systemd_envs }}"

- name: Create services files
  template: 
    src: "service.j2"
    dest: "{{ systemd_service_systemd_dir }}/{{ item.key }}.service"
  with_dict: "{{ systemd_services }}"

- name: Reload systemctl
  shell: echo "{{ systemd_service_systemd_dir }}/{{ item.key }}.service"
  with_dict: "{{ systemd_services }}"
  register: service_file
  notify:
    - reload systemctl